=== mono/winforms/datagrid/programes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Programes" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Programes">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ID " primary="yes" unique="yes" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="Nom" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="vilaweb" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Softcatala" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="Data" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="URL1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="150"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Versio" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Plataforma" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Categoria" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Subcategoria" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Llicencia" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Preu" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Mida" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Autor" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ProgramWeb" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Descripcio" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Notes" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Puntuacio" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="Imatge" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Descripcio_x0020_coregitda" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DescarregaAlt" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Projecte" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="250"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="URLMirror" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="150"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="AutorTraduccio" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== mono/winforms/datagrid/programes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="programes.xsd" generated="2005-03-29T11:07:22">
<Programes>
<ID>17</ID>
<Nom>Recull de termes de Softcatalà</Nom>
<vilaweb>1</vilaweb>
<Softcatala>1</Softcatala>
<Data>1999-04-17T00:00:00</Data>
<URL1>recull30.zip</URL1>
<Versio>3.0</Versio>
<Plataforma>6</Plataforma>
<Categoria>5</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>4</Llicencia>
<Preu>0</Preu>
<Mida>26406</Mida>
<Autor>Softcatalà</Autor>
<ProgramWeb>http://www.softcatala.org</ProgramWeb>
<Descripcio>És un recull de termes informàtics en anglès amb la corresponent
traducció al català, elaborat i actualitzat de manera continuada per 
Softcatalà. Aquests termes han estat extrets dels textos originals en 
anglès dels diferents programes que Softcatalà ha traduït fins ara, o 
que estan en procés de traducció.
&lt;br&gt;&lt;br&gt;
Aquest document és una eina important i útil per a l&apos;equip de traductors
de Softcatalà ja que inclou les traduccions de gairebé 1400 entrades,
algunes de les quals apareixen força sovint en els textos que cal traduir 
i per a les quals -de vegades- resulta força enrevessat de trobar una 
traducció adequada i coherent. En altres ocasions, les traduccions ja estan
normalitzades i Softcatalà es limita a deixar-ne constància en aquest
recull.
&lt;br&gt;&lt;br&gt;
La conveniència d&apos;aquesta eina es fa evident quan en la traducció d&apos;un
mateix producte informàtic -i a causa de la magnitud d&apos;aquest- hi
intervenen diferents traductors. El fet de poder consultar la mateixa font 
de dades permet assegurar que tots els implicats en un projecte determinat 
faran servir les mateixes traduccions per als mateixos termes a traduir, de 
manera que s&apos;optimitzarà la consistència dels textos.
&lt;br&gt;&lt;br&gt;
Veureu que alguns termes tenen més d&apos;una traducció al català, ja que el
camp de les traduccions no és una ciència exacta, però apareix en primer lloc
la més habitual o lògica. En altres ocasions veureu que alguns termes tenen
més d&apos;una entrada; això és degut al fet que la traducció al català varia en
funció del context en el qual aquests apareixen. Cal dir que totes les
traduccions s&apos;han d&apos;interpretar en l&apos;àmbit de la informàtica.
&lt;br&gt;&lt;br&gt;
Softcatalà compta amb el suport del Centre de Terminologia TERMCAT,
entitat que s&apos;encarrega de revisar el contingut del Recull de termes i suggerir
els canvis que considera oportuns, fruit de l&apos;acord de col·laboració que hi
ha entre aquestes dues entitats des de juny de 1999.</Descripcio>
<Puntuacio>5</Puntuacio>
<Descripcio_x0020_coregitda>1</Descripcio_x0020_coregitda>
</Programes>
<Programes>
<ID>18</ID>
<Nom>GR Disk Utility</Nom>
<vilaweb>1</vilaweb>
<Softcatala>0</Softcatala>
<Data>1999-04-18T00:00:00</Data>
<URL1>grudw31.zip</URL1>
<Versio>3.1</Versio>
<Plataforma>1</Plataforma>
<Categoria>6</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>2</Llicencia>
<Preu> (preu 29 dolars)</Preu>
<Mida>411989</Mida>
<Autor>GR Software</Autor>
<ProgramWeb>http://www.grsoftware.net/grduw.htm</ProgramWeb>
<Descripcio>GRDUW: Utilitat de disc shareware per a
Windows 95 V3.1 i Windows 32 bits (no
funciona sota Windows NT). Suport per
a disquets de 720Kb, 1.2Mb, 1.44Mb,
1.72Mb i MS-DMF (Microsoft Distribution
Format de 1.68Mb), i discs durs extraïbles;
duplica i compara disquets; enregistra i
carrega imatges binàries dels disquets;
torna a crear i comprova el sector
d&apos;engegada (boot); optimitza i verifica el
format del disc; dóna informació de disc
detallada; és capaç de reparar discs durs
i disquets; plena integració amb l&apos;explorador.</Descripcio>
<Puntuacio>4</Puntuacio>
<Imatge>grud.gif</Imatge>
<Descripcio_x0020_coregitda>1</Descripcio_x0020_coregitda>
</Programes>
<Programes>
<ID>19</ID>
<Nom>Pegasus Mail</Nom>
<vilaweb>1</vilaweb>
<Softcatala>0</Softcatala>
<Data>1999-04-18T00:00:00</Data>
<URL1>winca233.zip</URL1>
<Versio>2.33</Versio>
<Plataforma>1</Plataforma>
<Categoria>2</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>1</Llicencia>
<Preu>0</Preu>
<Mida>1588112</Mida>
<Autor>David Harris</Autor>
<Descripcio>Pegasus Mail és un programa de correu
electrònic per a sistemes Novell NetWare
i per a sistemes monousuari que utilitzen
una interfície Winsock TCP/IP. Aquest veterà
programa de correu inclou opcions molt útils,
com un revisor ortogràfic, suport de fitxers
de bústies amb format Unix, configuració
senzilla del servidor POP3/SMTP i suport per
a llistes de correu.</Descripcio>
<Puntuacio>3</Puntuacio>
<Imatge>peg.gif</Imatge>
<Descripcio_x0020_coregitda>1</Descripcio_x0020_coregitda>
</Programes>
<Programes>
<ID>20</ID>
<Nom>SemPoint</Nom>
<Softcatala>0</Softcatala>
<Data>1999-04-18T00:00:00</Data>
<URL1>sp225es.zip</URL1>
<Versio>2.25</Versio>
<Plataforma>2</Plataforma>
<Categoria>2</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>2</Llicencia>
<Preu> (preu 3600 ptes)</Preu>
<Mida>524029</Mida>
<Autor>Andrea Matta</Autor>
<Descripcio>SemPoint és el millor lector en
desconnexió per a Windows, útil tant
per a usuaris de BBS com per a punts
(o sysops) de FidoNet. És capaç de
manipular les aplicacions QWK,
BlueWave, Mc-Link&apos;s X)press i els
paquets dels grups de notícies
Usenet, així com bases de missatges
permanents en format *.MSG (Fido),
formats Hudson, Squish, JAM i
EzyCom! FÀCIL d&apos;utilitzar, però
molt potent!
Incorpora zip/unzip, UUEncode/Decode,
protecció PGP, funció de visualització
de text enriquit, classificació de
missatges i generador TIC.</Descripcio>
<Puntuacio>4</Puntuacio>
<Imatge>sem.gif</Imatge>
<Descripcio_x0020_coregitda>1</Descripcio_x0020_coregitda>
</Programes>
<Programes>
<ID>21</ID>
<Nom>Veterin</Nom>
<vilaweb>1</vilaweb>
<Softcatala>0</Softcatala>
<Data>1999-04-18T00:00:00</Data>
<URL1>veterin.zip</URL1>
<Versio>1.0</Versio>
<Plataforma>1</Plataforma>
<Categoria>3</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>1</Llicencia>
<Preu>0</Preu>
<Mida>4668796</Mida>
<Descripcio>És un programa per a la gestió d&apos;un Centre Veterinari que ens permet
tenir un catàleg de clients, dels animals que posseeixen, així com del
seu historial. Existeix un control de les vacunes que se li han
subministrat per poder efectuar posteriorment una publitramesa.</Descripcio>
<Puntuacio>3</Puntuacio>
<Imatge>veter.gif</Imatge>
<Descripcio_x0020_coregitda>1</Descripcio_x0020_coregitda>
</Programes>
<Programes>
<ID>22</ID>
<Nom>Recull de termes de l&apos;OS/2</Nom>
<vilaweb>1</vilaweb>
<Softcatala>0</Softcatala>
<Data>1999-04-18T00:00:00</Data>
<URL1>losos2.zip</URL1>
<Versio>1.0</Versio>
<Plataforma>6</Plataforma>
<Categoria>5</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>1</Llicencia>
<Preu>0</Preu>
<Mida>164812</Mida>
<Autor>IBM</Autor>
<ProgramWeb>http://www.ibm.com</ProgramWeb>
<Descripcio>Recull de termes d&apos;IBM per a l&apos;OS/2. Conté una llista dels termes en
anglès i la corresponent traducció al català que es van utilitzar per
traduir aquest sistema operatiu a la nostra llengua. D&apos;utilitat per
consultar termes tècnics en l&apos;àmbit de la informàtica, i si treballeu en
aquest entorn us servirà com a complement de l&apos;extens glossari que podeu
consultar des de l&apos;ajuda del mateix sistema.</Descripcio>
<Puntuacio>4</Puntuacio>
<Descripcio_x0020_coregitda>1</Descripcio_x0020_coregitda>
</Programes>
<Programes>
<ID>23</ID>
<Nom>QFacWin 2000</Nom>
<vilaweb>1</vilaweb>
<Softcatala>0</Softcatala>
<Data>1999-09-22T00:00:00</Data>
<URL1>fac2000.zip</URL1>
<Versio>4.1</Versio>
<Plataforma>1</Plataforma>
<Categoria>3</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>2</Llicencia>
<Preu> (preu 14.500 ptes)</Preu>
<Mida>6408336</Mida>
<Autor>Qsoft</Autor>
<ProgramWeb>http://www.qsoftnet.com</ProgramWeb>
<Descripcio>Programa de facturació amb aquestes caracteristiques:
&lt;br&gt;- Treball monousuari o en xarxa (v. professional)
&lt;br&gt;- Accés al programa per a usuaris i contrasenyes (configurable)
&lt;br&gt;- Preparat per a l&apos;EURO i l&apos;efecte 2.000
&lt;br&gt;- Multiempresa i possibilitat de multiexercici
&lt;br&gt;- Possibilitat de treballar amb pessetes o amb euros
&lt;br&gt;- Possibilitat de compartir arxius d&apos;articles, clients i proveïdors entre
vàries
&lt;br&gt;- empreses.
&lt;br&gt;- Amb suport per a Articles, Clients, Albarans, Factures, Proveïdors,
&lt;br&gt;- Compres i despeses.
&lt;br&gt;La nova versió 2000 conté aquestes novetats:
&lt;br&gt;- Gràfics comparatius i  configurables de vendes per clients, per mesos, per
articles, etc.
&lt;br&gt;- Rebuts. Es generen automàticament en afegir factures segons les formes de 
pagament i els dies de pagament del client.
&lt;br&gt; - Descomptes en cada línia d&apos; albarans, factures i compres.</Descripcio>
<Puntuacio>4</Puntuacio>
<Imatge>qfac2000.gif</Imatge>
<Descripcio_x0020_coregitda>1</Descripcio_x0020_coregitda>
</Programes>
<Programes>
<ID>24</ID>
<Nom>Diccionari Ispell en català d&apos;Ignasi Labastida</Nom>
<vilaweb>0</vilaweb>
<Softcatala>0</Softcatala>
<Data>1999-04-20T00:00:00</Data>
<URL1>ispellca.zip</URL1>
<Versio>0.1</Versio>
<Plataforma>1</Plataforma>
<Categoria>5</Categoria>
<Subcategoria>0</Subcategoria>
<Llicencia>1</Llicencia>
<Preu>0</Preu>
<Mida>2553664</Mida>
<Autor>Ignasi Labastida i Juan</Autor>
<Descripcio>Diccionari català per al programa Ispell, versió 0.1. L&apos;arxiu català és
una còpia de totes les paraules que componen el diccionari, extret d&apos;una
llista original elaborada per en Joan Dolç, i compactada amb
tots els afixos en l&apos;arxiu català. Totes les paraules del diccionari
estan en format de text.</Descripcio>
